- name: Hello World
  hosts : local
  connection: local
  tasks :
  - name: print hello World
    ansible.builtin.debug :
      msg : "Hello World"

- name: Play 2
  hosts : local
  connection: local
  tasks :
  - name: print hello World Play 2
    ansible.builtin.debug :
      msg : "Hello World from Play 2"